env: flex
runtime: gs://elixir-runtime/elixir.yaml
runtime_config:
    release_app: station_api
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
includes:
    - secrets.yaml
