version: '2'
volumes:
  db:
services:
  api:
    build: .
    command: mix phx.server
    ports:
      - 4000:4000
    restart: always
    links:
      - db
  db:
    image: mysql:5.7.25
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: station_api_dev
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - db:/var/lib/mysql
        - ./migrations:/docker-entrypoint-initdb.d
