version: "2"
services:
  api:
    build: .
    ports:
      - 3000:3000
    restart: always
    links:
      - db
  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: station_api_dev
      MYSQL_USER: station_api_dev
      MYSQL_PASSWORD: station_api_dev
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
